### ISSUE TITLE
Support the union schema (from Hono 4.6.5)

### ISSUE THREAD

**Issue by wighawag** [miyaji255/hono-typia-openapi#9]
Here is the reproduction repo: https://github.com/bug-reproduction/hono-typia-openapi-test

```
git clone https://github.com/bug-reproduction/hono-typia-openapi-test
cd hono-typia-openapi-test
pnpm i
pnpm openapi
# see ./openapi.json
```

**Comment by miyaji255** [comment]
Sorry, I will deal with the inferred types for simplicity's sake.

**Comment by wighawag** [comment]
Sorry for the confusion but the type used  is actually infered, I just outputed it in ts format to make the reproduction step easier.

Otherwise I would have to import my whole project.

**Comment by miyaji255** [comment]
Oh, sorry about that. I investigated based on your code and found that it was caused by the following PR that changed the intersection type to the union type. Thank you for the info!

https://github.com/honojs/hono/pull/3443
